# Theta configuration
genesis:
  hash: "0xa58cb754a23975c872ef06d8b54baf16eec88ad60f966368b950a6c16ae52ed9"
storage:
  statePruningRetainedBlocks: 2048
p2p:
  port: 16000
  seeds: 54.219.137.110:15872
rpc:
  enabled: true
log:
  levels: "*:info"
